name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore Ahorcado/Ahorcado.sln
    
    - name: Build
      run: dotnet build Ahorcado/Ahorcado.sln --configuration Release
      
    - name: Test
      run: dotnet test Ahorcado/Ahorcado.sln --configuration Release --logger "trx;LogFileName=test-results.trx" || true
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
        
    - name: Test Collect
      run: dotnet test Ahorcado/Ahorcado.sln --collect:"XPlat Code Coverage"
      
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.12
      with:
        # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        reports: "**/coverage.cobertura.xml"
        # The directory where the generated report should be saved.
        targetdir: "coveragereport"
        # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
        reporttypes: Html
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: "coveragereport"
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/coveragereport"
        # The desired behavior if no files are found using the provided path.
