name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore Ahorcado/Ahorcado.sln
    
    - name: Build
      run: dotnet build Ahorcado/Ahorcado.sln --configuration Release
      
    - name: Test
      run: dotnet test Ahorcado/Ahorcado.sln --configuration Release --logger "trx;LogFileName=test-results.trx" || true
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
